# Note that Dependabot is only updating Gemfile.lock which given that this is a library, has no impact on
# downstream dependencies whatsoever (only the gemspec does)
# The Gemfile.lock is only here for a consistent development experience of the library itself

# merge minor development dependency updates
- match:
    dependency_type: development
    update_type: semver:minor # includes patch updates!

# merge minor production and security dependency updates
- match:
    dependency_type: production
    update_type: semver:minor

- match:
    dependency_type: production
    update_type: security:minor
