version: 2.1

orbs:
  ruby: circleci/ruby@1.0
  node: circleci/node@2
  cst: cst/framework@1

workflows:
  version: 2
  yeet-le-jobs:
    jobs:
      - cst/enforce-gem-version-bump
      - cst/rspec-ruby:
          rspec-system-args: "SIMPLE_COV_RUN=true"
          cc-report-collect-ruby: "3.2.3"
          matrix:
            parameters:
              ruby-version: ["3.2.3" , "3.2"]
            alias: required-matrix-tests
          name: test-ruby<< matrix.ruby-version >>
      - cst/publish-gem:
          publish-git: true
          publish-default-gem: true
          requires:
            - required-matrix-tests
          filters:
            branches:
              only:
                - main
